# Generated by Django 5.1.3 on 2024-11-21 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('publicate', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
