# Generated by Django 5.1.3 on 2024-12-04 16:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('full_name', models.CharField(max_length=200)),
                ('comment', models.TextField(default='')),
                ('owner', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('owner', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_and_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('delay', models.CharField(choices=[('day', 'Once Day'), ('week', 'Once Week'), ('month', 'Once Month')], default='day', max_length=5)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('finished', 'Finished')], default='created', max_length=10)),
                ('owner', models.EmailField(max_length=254)),
                ('client', models.ManyToManyField(to='mailings.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailings.message')),
            ],
        ),
        migrations.CreateModel(
            name='MailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2024, 12, 4, 19, 40, 59, 401371), null=True)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error')], max_length=5)),
                ('response', models.TextField(null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailings.mailing')),
            ],
        ),
    ]
