# Generated by Django 5.1.3 on 2024-11-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingtry',
            name='owner',
        ),
        migrations.AddField(
            model_name='mailingtry',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
