# Generated by Django 5.1.3 on 2024-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailingtry_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='end_date_and_time',
        ),
    ]
