# Generated by Django 5.1.3 on 2024-11-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_remove_mailing_end_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='job_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
