# Generated by Django 5.1.3 on 2024-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailing_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='job_id',
        ),
    ]
