# Generated by Django 5.1.3 on 2024-11-26 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_remove_mailing_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtry',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 18, 26, 46, 288793), null=True),
        ),
    ]
