# Generated by Django 5.1.3 on 2024-11-27 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0008_alter_mailingtry_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtry',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 15, 44, 59, 501956), null=True),
        ),
    ]
