# Generated by Django 5.1.3 on 2024-11-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manager_permissions', 'See all users and mailing, can block user, can stop mailing')]},
        ),
    ]
